### ISSUE TITLE
Using `incoming.podlets`

### ISSUE THREAD

**Issue by digitalsadhu** [Jozzeh/micro-frontends-divers#1]
https://github.com/Jozzeh/micro-frontends-divers/blob/master/fullapp/routes/home.js#L80-L83

Where you have:
```js
content.forEach(element => {
      incoming.css = incoming.css.concat(element.css);
      incoming.js = incoming.js.concat(element.js);
})
```

You should be able to streamline this like so:
```js
incoming.podlets = content
```

See: https://podium-lib.io/docs/api/assets

**Comment by Jozzeh** [comment]
Thanks! Changed it.
