### ISSUE TITLE
Unable to run project in my local system

### ISSUE THREAD

**Issue by mohatasuraj** [Jozzeh/micro-frontends-divers#11]
![image](https://user-images.githubusercontent.com/14251390/91527270-15609600-e923-11ea-8614-fb7cea97c8de.png)

Please guide me how can i run this project in local system

**Comment by Jozzeh** [comment]
As written in the readme, if you are on windows each of the commands in the startAll script need to be run separately in prompt/terminal window...   

**startAll**  
(cd ./sveltepod && npm run podiumstart)   
(cd ./reactpod && npm run podiumstart)   
(cd ./reactnav && npm run podiumstart)   
(cd ./htmlpod && npm run podiumstart)   
(cd ./htmlbuspod && npm run podiumstart)   
(cd ./vuepod && npm run podiumstart)   
(cd ./angularpod && npm run podiumstart)   
(cd ./fullapp && npm run start)  

A different solution might be to separate the commands in their own scripts and then use a package such as [run-all](https://www.npmjs.com/package/npm-run-all) to run them all in parallel.   

-  

I recommend this repo where several front-end frameworks & libraries are combined:   
https://github.com/Jozzeh/podium-mixed-example  

It is accompanied by this article:  
https://medium.com/swlh/react-vue-svelte-on-one-page-with-micro-frontends-f740b3ee6979
