### ISSUE TITLE
Communication between podlets

### ISSUE THREAD

**Issue by enchobelezirev** [Jozzeh/micro-frontends-divers#20]
Hello @Jozzeh,

In my team we have integrated Podium podlets in order to achieve micro frontend architecture. The problem is the concept for realizing communication between different micro frontends on different pages. We want the communication to happen using the @podium/browser but currently we have not found a solution to this. The reason is that when redirecting between frontends, the page is being reloaded and thus all the messages are lost. Meaning, when I am publishing some message on micro frontend A, located on page /a, when I redirect to micto frontend B,located on page /b, I cannot see the message in the micro frontend B because the page is being reloaded.
Can you tell me whether we can implement such communication via @podium/browser or it is a lost cause?
Something more, is there another solution which we could explore if we want to achieve such communication?

Thanks and best regards,
Encho

**Comment by Jozzeh** [comment]
Hi,  

The @podium/browser package is a way of communicating between micro frontends within the same browser window. 
The message sent instantly and if no other podlet is available to listen to it... then the message is lost.  
I guess it resembles sending custom (synthetic) events in the window (https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events ). 

Anyway, communication over several pages will be very difficult to achieve using the @podium/browser package and I don't think it is even possible.  
If you would like to share data between podlets even after a page refresh/redirect, I'd suggest using localStorage.  
( https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage )  

In localStorage, you can set strings (such as stringified JSON), and this will be accessible over pages.   
LocalStorage will even be saved over several sessions. This means the user can close the browser, and the next time the user visits the page again, the localStorage will still be available.  
Careful though: localStorage is lost after a single session when the user browses in incognito mode or if the browser history has been completely wiped. 

( if you really do not want to use localStorage, you can store some data in session cookies as well.)

Good luck,  


Jos

**Comment by enchobelezirev** [comment]
Thanks :)
